llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  base_url: "https://api.openai.com/v1" 
  api_key: "YOUR_API_KEY"
  model: "gpt-4o"  # or gpt-3.5-turbo
  # timeout: 600 # Optional. If set to 0, default value is 300.
  # Details: https://azure.microsoft.com/en-us/pricing/details/cognitive-services/openai-service/
  pricing_plan: "" # Optional. Use for Azure LLM when its model name is not the same as OpenAI's

# Football Avatar Configuration
avatar:
  api_endpoint: "http://localhost:8000/speak"
  default_language: "Chinese"
  emotion_mappings:
    goal: "excited"
    card: "serious"
    substitution: "neutral"
    save: "surprised"
    halftime: "neutral"
    tactical: "analytical"
    stat: "informative"
    transition: "friendly"
    penalty: "intense"

n8n:
  webhook_url: "http://localhost:5678/webhook/match"
  event_types:
    - "goal"
    - "card"
    - "substitution"
    - "save"
    - "halftime"
    - "tactical"
    - "stat"
    - "transition"
    - "penalty"

mcp:
  server_url: "http://localhost:8080"
  tools:
    - "process_match_event"
    - "trigger_avatar"
